name: Filter CISA RSS to Slack

on:
  workflow_dispatch:

jobs:
  filter-and-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Restore deduplication cache
        uses: actions/cache@v3
        with:
          path: .seen_entries_cisa.json
          key: seen-entries-cisa-${{ github.run_id }}
          restore-keys: |
            seen-entries-cisa-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run CISA RSS filter and post to Slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
          JIRA_URL: ${{ secrets.JIRA_URL }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_EPIC_KEY: ${{ secrets.JIRA_EPIC_KEY }}
          JIRA_PROJECT_KEY: ${{ secrets.JIRA_PROJECT_KEY }}
        run: python filter_rss_cisa.py

      - name: Save deduplication cache
        uses: actions/cache/save@v3
        if: always()
        with:
          path: .seen_entries_cisa.json
          key: seen-entries-cisa-${{ github.run_id }} 